# FILE: tests/test_repro_para_id_signed_int32.py
"""
Repro tests for BUG_paraId_signed_int32_thread_collapse.md (B5, 2026-08-12,
Adeu 2.2.0 / 0db3cc2) — the CI half. The Word-verified half lives in
tests/test_live_word_para_id_signed_int32.py and needs Windows + Word.

`_generate_para_id` and `_generate_rsid` drew from `0 .. 0xFFFFFFFF`. Word
parses every `ST_LongHexNumber` as a SIGNED 32-bit integer and ECMA-376
requires the value to be greater than `0x00000000` and less than `0x80000000`,
so roughly HALF of every paraId Adeu minted was thrown away and regenerated by
Word on load — dangling every `w15:paraIdParent` that pointed at it and
dropping the reply out of its thread.

This is the third occurrence of one root cause:

    2026-08-11 B3   w16cid:durableId   comment anchor collapses to a point
    2026-08-12 B5   w14:paraId         reply threading collapses
    2026-08-12 B5   w:rsid*            no observed symptom; masked anyway

B3 was fixed as a POINT FIX to one attribute, and the reasoning behind it
("paraId and rsid are opaque 32-bit tokens with no such constraint") was
recorded as settled fact in two docstrings, AI_CONTEXT.md, and two tests that
went red when the bug was fixed. The point of this file is that it does not
care which attribute is the special one: `test_saved_package_carries_no_out_of
_range_long_hex_numbers` scans EVERY ST_LongHexNumber in the saved package, and
would have caught all three instances on the day they shipped.

Test-first: every assertion here fails on the pre-fix engine.
"""

import io
import random
import re

import pytest
from docx import Document

from adeu.models import ModifyText, ReplyComment
from adeu.redline.comments import CommentsManager
from adeu.redline.engine import RedlineEngine
from adeu.utils.long_hex_number import (
    ST_LONG_HEX_NUMBER_MAX,
    ST_LONG_HEX_NUMBER_MIN,
    is_word_readable_long_hex_number,
    to_long_hex_number,
)
from tests.utils import (
    assert_word_readable_ids,
    edge_of_range_randint,
    find_out_of_range_long_hex_numbers,
)

#: Word's rule for every ST_LongHexNumber, from ECMA-376: "shall be greater
#: than 0x00000000 and less than 0x80000000". Restated here as LITERALS on
#: purpose: the engine and the package scanner both derive their bounds from
#: adeu.utils.long_hex_number, so a wrong constant there would agree with
#: itself and pass. TestTheRuleItself is what stops that.
LEGAL_MIN = 0x00000001
LEGAL_MAX = 0x7FFFFFFF

#: 256 samples: a generator drawing from the full 32-bit range fails a
#: high-bit assertion with probability 1 - 2^-256, i.e. deterministically.
SAMPLES = 256

BODY = "The parties shall confer in good faith before moving to compel production."
TARGET = "confer in good faith"


def doc_stream(*paragraphs: str) -> io.BytesIO:
    doc = Document()
    for text in paragraphs or (BODY,):
        doc.add_paragraph(text)
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf


def manager() -> CommentsManager:
    return CommentsManager(Document())


def threaded_package(reply_count: int = 2) -> bytes:
    """A saved package with one comment thread carrying `reply_count` replies."""
    engine = RedlineEngine(doc_stream(), author="Sarah Chen")
    engine.apply_edits([ModifyText(target_text=TARGET, new_text=TARGET, comment="Root note.")])
    root_id = next(iter(engine.comments_manager.extract_comments_data()))
    engine.author = "Adeu AI"
    for i in range(reply_count):
        engine.apply_review_actions([ReplyComment(target_id=f"Com:{root_id}", text=f"Reply {i}.")])
    return engine.save_to_stream().getvalue()


def offenders(values, label: str) -> str:
    bad = [v for v in values if not LEGAL_MIN <= int(v, 16) <= LEGAL_MAX]
    return (
        f"{len(bad)}/{len(values)} generated {label}s are outside "
        f"(0x00000000, 0x80000000) — e.g. {bad[:4]}. Word parses ST_LongHexNumber as a SIGNED "
        "32-bit integer: it discards these on load and regenerates them, breaking every "
        "reference that pointed at them."
    )


# ---------------------------------------------------------------------------
# The rule itself
# ---------------------------------------------------------------------------


class TestTheRuleItself:
    """
    `adeu.utils.long_hex_number` is the single definition of "an id Word will
    keep": the generators mint against it and the package scanner audits
    against it. That is the right structure, and it has one failure mode — a
    wrong constant would be consistent with itself everywhere. Everything here
    checks it against LITERALS taken from the spec text, not against itself.
    """

    def test_the_bounds_are_the_ones_ecma_376_states(self):
        assert (ST_LONG_HEX_NUMBER_MIN, ST_LONG_HEX_NUMBER_MAX) == (LEGAL_MIN, LEGAL_MAX), (
            "ECMA-376: the value shall be greater than 0x00000000 and less than 0x80000000"
        )

    @pytest.mark.parametrize(
        "value, readable, why",
        [
            ("00000000", False, "forbidden: Word rejects the whole package"),
            ("00000001", True, "smallest legal value"),
            ("12345678", True, "ordinary value"),
            ("7FFFFFFF", True, "largest legal value"),
            ("80000000", False, "smallest illegal value — exactly one greater"),
            ("D2AEAE20", False, "the id from the field report that collapsed the thread"),
            ("FFFFFFFF", False, "all bits set"),
            ("", False, "not a value at all"),
            ("1234567", True, "short forms are legal; Word writes them padded"),
            ("123456789", False, "too long for xsd:hexBinary length 4"),
            ("ZZZZZZZZ", False, "not hexadecimal"),
        ],
    )
    def test_the_predicate_agrees_with_the_specification(self, value, readable, why):
        assert is_word_readable_long_hex_number(value) is readable, why

    @pytest.mark.parametrize(
        "value, folded",
        [
            (0x00000000, "00000001"),  # 0 is forbidden, so it cannot be the identity
            (0x00000001, "00000001"),
            (0x7FFFFFFF, "7FFFFFFF"),
            (0x80000000, "00000001"),  # masks to 0, which is forbidden -> MIN
            (0x80000001, "00000001"),
            (0xFFFFFFFF, "7FFFFFFF"),
            (0xFC855CFC, "7C855CFC"),  # the first id Node's cell anchor derived
        ],
    )
    def test_folding_a_derived_value_lands_in_range(self, value, folded):
        """`to_long_hex_number` is for ids that are DERIVED rather than drawn —
        Node's `{#cell:paraId}` FNV fallback is the caller. Clearing the high
        bit is what Word effectively does anyway."""
        assert to_long_hex_number(value) == folded
        assert is_word_readable_long_hex_number(to_long_hex_number(value))


# ---------------------------------------------------------------------------
# The generators
# ---------------------------------------------------------------------------


class TestGeneratorRanges:
    """
    Every `ST_LongHexNumber` Adeu mints must land in `(0x00000000,
    0x80000000)`. Parametrised over all three generators deliberately: the way
    this bug shipped was a fix applied to exactly one of them, so a per-
    attribute test is how the class survives.
    """

    @pytest.mark.parametrize("generator", ["_generate_para_id", "_generate_rsid", "_generate_durable_id"])
    def test_generated_ids_are_valid_st_long_hex_numbers(self, generator):
        mint = getattr(manager(), generator)
        values = [mint() for _ in range(SAMPLES)]
        assert all(LEGAL_MIN <= int(v, 16) <= LEGAL_MAX for v in values), offenders(
            values, generator.removeprefix("_generate_")
        )

    @pytest.mark.parametrize("generator", ["_generate_para_id", "_generate_rsid", "_generate_durable_id"])
    def test_generated_ids_are_eight_upper_case_hex_digits(self, generator):
        mint = getattr(manager(), generator)
        for _ in range(64):
            value = mint()
            assert re.fullmatch(r"[0-9A-F]{8}", value), (
                f"{generator} produced {value!r}, which is not an 8-digit upper-case ST_LongHexNumber"
            )

    @pytest.mark.parametrize("generator", ["_generate_para_id", "_generate_rsid", "_generate_durable_id"])
    def test_no_generator_can_return_zero(self, generator, monkeypatch):
        """
        `00000000` is forbidden as explicitly as the high half, and it is the
        one value in this class Word does NOT paper over: a comment paragraph
        with `w14:paraId="00000000"` makes Word declare the file corrupted and
        refuse to open it (Word-verified). `randint(0, …)` can return it.
        """
        # The smallest value this generator can possibly emit.
        monkeypatch.setattr(random, "randint", lambda a, b: a)
        assert getattr(manager(), generator)() != "00000000", (
            f"{generator} can mint 00000000. Word rejects the whole package: the generator must start at 1, not 0."
        )

    def test_every_generator_draws_from_the_same_range(self, monkeypatch):
        """
        The class-level guard. B3 was fixed by giving ONE attribute its own
        masked generator and writing down that the others did not need it —
        which is precisely how B5 shipped. Pinning that the generators agree
        makes 'narrow one, leave the others' fail at the next attempt.
        """
        names = ("_generate_para_id", "_generate_rsid", "_generate_durable_id")
        for edge, expected in ((lambda a, b: a, "00000001"), (lambda a, b: b, "7FFFFFFF")):
            monkeypatch.setattr(random, "randint", edge)
            mgr = manager()
            bounds = {name: getattr(mgr, name)() for name in names}
            assert set(bounds.values()) == {expected}, (
                f"the generators do not share a bound: {bounds}. Every ST_LongHexNumber goes "
                "through one generator; there is no attribute for which the high half is safe."
            )


# ---------------------------------------------------------------------------
# The general guard — what would have caught all three instances
# ---------------------------------------------------------------------------


class TestSavedPackageIds:
    def test_saved_package_carries_no_out_of_range_long_hex_numbers(self):
        """
        Attribute-agnostic, end-to-end: scan every `.xml` part of a saved
        package for every attribute typed `ST_LongHexNumber` and require all of
        them to be in range. Prefer this to three attribute-specific tests — it
        is what turns a third point fix into a closed class.
        """
        assert_word_readable_ids(threaded_package(), context="threaded document: ")

    @pytest.mark.parametrize("high", [True, False], ids=["top-of-range", "bottom-of-range"])
    def test_no_call_site_can_reach_an_unmasked_generator(self, high, monkeypatch):
        """
        `random.randint` is pinned to one END of whatever range each generator
        asks for — always a value that call could legitimately have returned.
        A generator over `0 .. 0xFFFFFFFF` then mints `FFFFFFFF…` (high) or
        `00000000…` (low); a masked one mints `7FFFFFFF…` / `00000001…`.

        Because the substitution is global, this covers every mint site that
        `add_comment` can reach — not just the ones a reviewer remembered — and
        it fails deterministically rather than 50% of the time.
        """
        monkeypatch.setattr(random, "randint", edge_of_range_randint(high=high))
        assert_word_readable_ids(threaded_package(reply_count=3), context=f"{'high' if high else 'low'} RNG: ")

    @pytest.mark.parametrize(
        "attribute",
        ["w14:paraId", "w14:textId", "w15:paraIdParent", "w16cid:durableId", "w:rsidR", "w:rsidSect"],
    )
    @pytest.mark.parametrize("value", ["80000000", "FFFFFFFF", "00000000"])
    def test_the_package_scanner_detects_every_shape_of_bad_id(self, attribute, value):
        """
        Guards the guard. A scanner that silently matched nothing would make
        every test above vacuous, and a bug class that hides behind a check
        which never fires is exactly what this file exists to stop. Built from
        a synthetic package so it measures the SCANNER, not the engine.
        """
        package = self._synthetic_package(f'<w:p {attribute}="{value}"/>')
        assert [(attr, val) for _part, attr, val in find_out_of_range_long_hex_numbers(package)] == [(attribute, value)]

    @pytest.mark.parametrize("value", ["00000001", "7FFFFFFF", "12345678"])
    def test_the_package_scanner_accepts_legal_ids(self, value):
        package = self._synthetic_package(f'<w:p w14:paraId="{value}"/>')
        assert find_out_of_range_long_hex_numbers(package) == []

    def test_the_package_scanner_reads_the_w_rsids_element_form(self):
        """`<w:rsid w:val="…"/>` in settings.xml carries the same type in an
        element rather than on the paragraph. Adeu does not write it today;
        the scanner covers it so that the day something does, it is checked."""
        package = self._synthetic_package('<w:rsids><w:rsidRoot w:val="C0000001"/></w:rsids>')
        assert [attr for _part, attr, _v in find_out_of_range_long_hex_numbers(package)] == ["w:rsidRoot/@w:val"]

    @staticmethod
    def _synthetic_package(fragment: str) -> bytes:
        import zipfile

        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, "w") as archive:
            archive.writestr("word/document.xml", f"<w:document>{fragment}</w:document>")
            # Non-XML parts must be skipped, not decoded as text.
            archive.writestr("word/media/image1.png", b"\x89PNG\r\n\x1a\n\xff\xff\xff\xff")
        return buffer.getvalue()

    def test_a_document_with_no_comments_is_already_clean(self):
        """
        Baseline: the ids Adeu inherits from python-docx's template (rsids in
        settings/styles, the body paragraph ids) are all in range, so a failure
        of the scan above can only be something Adeu minted.
        """
        engine = RedlineEngine(doc_stream(), author="Adeu AI")
        engine.apply_edits([ModifyText(target_text="good faith", new_text="good faith and candor")])
        assert_word_readable_ids(engine.save_to_stream().getvalue(), context="no comments: ")


# ---------------------------------------------------------------------------
# Threading: the consumer-visible symptom
# ---------------------------------------------------------------------------


class TestThreadingIdsResolve:
    W15 = "http://schemas.microsoft.com/office/word/2012/wordml"

    @staticmethod
    def _comment_ex(package: bytes):
        import zipfile

        with zipfile.ZipFile(io.BytesIO(package)) as archive:
            name = next(n for n in archive.namelist() if "commentsExtended" in n)
            xml = archive.read(name).decode("utf-8")
        return re.findall(r'w15:paraId="([0-9A-Fa-f]{8})"(?:\s+w15:paraIdParent="([0-9A-Fa-f]{8})")?', xml)

    def test_every_reply_points_at_an_in_range_parent_para_id(self):
        """
        64 independent threads, so a generator that is right half the time
        cannot pass by luck (2^-64). B1 already guarantees a reply carries
        `w15:paraIdParent`; what this adds is that the value it points AT is
        one Word will still recognise after load. A reply can be perfectly
        parented in the XML and still not thread.
        """
        dangling = []
        for _ in range(64):
            entries = self._comment_ex(threaded_package(reply_count=1))
            roots = {para_id for para_id, parent in entries if not parent}
            for para_id, parent in entries:
                if not parent:
                    continue
                assert parent in roots, f"reply {para_id} points at unknown parent {parent}"
                if not LEGAL_MIN <= int(parent, 16) <= LEGAL_MAX:
                    dangling.append(parent)
                if not LEGAL_MIN <= int(para_id, 16) <= LEGAL_MAX:
                    dangling.append(para_id)

        assert not dangling, (
            f"{len(dangling)}/64 threads reference a paraId Word will discard: {dangling[:4]}. "
            "The reply IS parented — process_batch reports success and B1's CommentThreadingError "
            "correctly does not fire — it just stops being a reply the moment Word opens the file."
        )

    def test_a_legacy_parent_adopted_for_threading_gets_an_in_range_para_id(self, monkeypatch):
        """
        The second mint site: a parent comment with no `w14:paraId` (pre-2013
        Word, or any generator without the modern-comments extensions) has one
        minted for it so the reply can thread (`_adopt_into_modern_comments`).
        That id is the thread ROOT, the worst place for a bad one — an
        out-of-range root takes every reply in the thread down with it.
        """
        engine = RedlineEngine(doc_stream(), author="Sarah Chen")
        engine.apply_edits([ModifyText(target_text=TARGET, new_text=TARGET, comment="Legacy note.")])
        source = engine.save_to_stream()

        # Strip the paraId to produce the legacy comment shape.
        from docx.oxml.ns import qn

        source.seek(0)
        doc = Document(io.BytesIO(source.getvalue()))
        comments_part = next(
            p for p in doc.part.package.parts if p.content_type.endswith("wordprocessingml.comments+xml")
        )
        from docx.opc.part import XmlPart
        from docx.oxml import parse_xml

        element = parse_xml(comments_part.blob)
        stripped = 0
        for comment in element.findall(qn("w:comment")):
            for para in comment.findall(qn("w:p")):
                if para.get(qn("w14:paraId")) is not None:
                    del para.attrib[qn("w14:paraId")]
                    stripped += 1
        assert stripped, "fixture precondition: nothing to strip"

        replacement = XmlPart(comments_part.partname, comments_part.content_type, element, comments_part.package)
        package = comments_part.package
        package.parts[package.parts.index(comments_part)] = replacement
        for rel in doc.part.rels.values():
            if not rel.is_external and rel.target_part is comments_part:
                rel._target = replacement
        legacy = io.BytesIO()
        doc.save(legacy)
        legacy.seek(0)

        monkeypatch.setattr(random, "randint", edge_of_range_randint(high=True))
        engine = RedlineEngine(legacy, author="Adeu AI")
        parent_id = next(iter(engine.comments_manager.extract_comments_data()))
        applied, skipped, _ = engine.apply_review_actions(
            [ReplyComment(target_id=f"Com:{parent_id}", text="Addressed.")]
        )
        assert (applied, skipped) == (1, 0), "the reply did not apply at all"

        assert_word_readable_ids(engine.save_to_stream().getvalue(), context="adopted legacy parent: ")
